name: Update GitHub stats

on:
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate GitHub stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&count_private=true&show=reviews,prs_merged,prs_merged_percentage&hide_border=true&bg_color=00000000&title_color=0969da&text_color=57606a&icon_color=0969da
          path: dist/github-stats.svg
          token: ${{ secrets.PROFILE_STATS_TOKEN }}
          fail_on_error: true

      - name: Publish stats to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
